### PR TITLE
HW4_Tests

### PR DESCRIPTION
**Pull request by MaxSihua**

### CODE REVIEW

**Comment by IhorOsadchyi** [comment]
As for me, using real database for unit testing - bad idea! The main idea of unit testing to check that some functionality are working as expected with abstraction from 3rd party systems. The best way to do it - mock responses from such systems with mock data. This data could be different for different test cases so you can check edge cases and be sure that you functions properly works.

**Comment by MaxSihua** [comment]
> As for me, using real database for unit testing - bad idea! The main idea of unit testing to check that some functionality are working as expected with abstraction from 3rd party systems. The best way to do it - mock responses from such systems with mock data. This data could be different for different test cases so you can check edge cases and be sure that you functions properly works.
@IhorOsadchyi 

I was trying to mock response  from DB by using  supertest and mongodb-memory-server, but I was never able to make it work properly and trying all the possible solutions, the mighty internet offered, for my problems was only fueling this cascade of problems. So I decided to stick with this solution.

**Comment by IhorOsadchyi** [comment]
I'm not sure you need mongodb-memory-server for it. You can mock responses with jest. 

Probably next articles will help to figure out how:

https://dev.to/darkmavis1980/how-to-test-mongoose-models-with-jest-and-mockingoose-2k10
https://www.sammeechward.com/mocking-a-database-with-jest-in-javascript

There are also a lot of search result about how to mock mongodb/mongoose responses for test reasons - https://www.google.com/search?q=mock+mongoose+methods+responses+with+jest&newwindow=1&sca_esv=593947850&ei=d_OLZeXIO7qii-gP6NqC-AU&ved=0ahUKEwil4KXeq6-DAxU60QIHHWitAF8Q4dUDCBA&uact=5&oq=mock+mongoose+methods+responses+with+jest&gs_lp=Egxnd3Mtd2l6LXNlcnAiKW1vY2sgbW9uZ29vc2UgbWV0aG9kcyByZXNwb25zZXMgd2l0aCBqZXN0MgUQIRigATIFECEYoAEyBRAhGJ8FSJ4-UABY7zlwAXgBkAEAmAF4oAHRCaoBAzguNbgBA8gBAPgBAcICCBAAGIAEGKIE4gMEGAAgQYgGAQ&sclient=gws-wiz-serp

**Comment by MaxSihua** [comment]
@IhorOsadchyi I redid the tests according to the comments

**Review by IhorOsadchyi — APPROVED** [review]

**Pull request merged**
